apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: webapp:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET_KEY_BASE64
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: jwt-secret-key-base64
            - name: DB_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: db-dialect
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: database-url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100