CREATE TABLE "users" (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    hashed_password VARCHAR(255)
);

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255),
    hashed_token VARCHAR(255),
    created_at BIGINT,
    expires_at BIGINT
);

CREATE TABLE todo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    description VARCHAR(255),
    target_date DATE,
    done BOOLEAN default false
);